# -*- coding: utf-8 -*-
"""Assignment3_scd.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R_-XdlJ5zbbh7_BBWHQ9wXuAUwy_77hA
"""

class User:
    def __init__(self, username, password, user_role):
        self.username = username
        self.password = password
        self.user_role = user_role
        self.posts = []

    def create_post(self, content):
        self.posts.append(Post(content, self))

    def like_post(self, post):
        post.likes.append(self)

    def display_posts(self):
        for post in self.posts:
            print(post.content)

    def promote_user(self, user):
        if isinstance(self, Admin):  # Check if the current user is an Admin
            user.user_role = "admin"
        else:
            print("You do not have permission to perform this action.")


class Post:
    def __init__(self, content, author):
        self.content = content
        self.author = author
        self.likes = []

    def display_likes(self):
        for user in self.likes:
            print(user.username)


class RegularUser(User):
    def __init__(self, username, password):
        super().__init__(username, password, "regular user")


class Admin(User):
    def __init__(self, username, password):
        super().__init__(username, password, "admin")


user1 = RegularUser("user1", "password1")
user2 = RegularUser("user2", "password2")
admin = Admin("admin", "admin_password")


user1.create_post("post from user1.")
user2.create_post("post from user2.")

user2.like_post(user1.posts[0])
admin.like_post(user2.posts[0])


print("Liked posts:")
user1.display_posts()
user2.display_posts()


user2.promote_user(user1)